
module.exports={
    FRESHDESK_DOMAIN_URL : "https://myfreshdeskzone.freshdesk.com",
    MONGODB_URL : "mongodb://dev:passw0rd@ds125255.mlab.com:25255/mydatabase",
    FRESHDESK_ENDPOINT : "myfreshdeskzone",
    FD_TICKET_PATH : "/api/v2/tickets",
    CHANNEL_NAME : "crosstalk",
    LATE_NIGHT : "Late Night",
    GREETING : "Hello buddy!",
    API_AI_SESSION_ID : 'tabby_cat',
    INTENT_REFUND_REQUEST : "Refund request",
    MESSAGE_FOR_VALID_EMPLOYEE : "Welcome ! How can i help you?",
    MESSAGE_FOR_INVALID_EMPLOYEE : "Sorry for the inconvenience ! Could you please enter a valid Employee ID?",
    ERROR_MESSAGE : "Something went wrong! Please try again later",
    INTENT_ADHOC : "AdhocReasons",
    INTENT_ADHOC_LOCATION : "location",
    SERVICE_ADHOC : "Adhoc",
    INTENT_LATE_NIGHT_TIMING : "latenightCabTimings",
    INTENT_LATE_NIGHT_DATE : "latenightCabDate",
    SERVICE_LATE_NIGHT : "Late Night",
    RESPONSE_YES : "yes",
    TICKET_EMAIL : 'rg@siriuscom.com',
    TICKET_SUBJECT : 'Cab Request',
    TICKET_DESCRIPTION : 'Ticket for Cab Request',
    TICKET_STATUS : 2,
    TICKET_PRIORITY : 1,
    RESPONSE_NO : "no",
    MESSAGE_CANCELLATION : "Request for Cab Booking is cancelled",
    LATE_SHIFT : "Late Night Shift"
};
